Repository KCC-Team/KCC-PMS, pull requests merged in 2024-11, with the labels that each got.

#235 [#234] 결함 도메인 개선사항 적용
  src/main/java/com/kcc/pms/domain/common/config/EnvVariableProperties.java
  src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
  src/main/java/com/kcc/pms/domain/common/mapper/CommonMapper.java
  src/main/java/com/kcc/pms/domain/common/service/CommonServiceImpl.java
  src/main/java/com/kcc/pms/domain/common/util/AwsS3Utils.java
  src/main/java/com/kcc/pms/domain/output/mapper/FileMapper.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/mapper/common/FileMapper.xml
  src/main/resources/mapper/task/DefectMapper.xml
  src/main/webapp/WEB-INF/views/common.jsp
  src/main/webapp/WEB-INF/views/defect/defect.jsp
  src/main/webapp/WEB-INF/views/defect/list.jsp
  src/main/webapp/WEB-INF/views/output/file/file-task.jsp
  src/main/webapp/WEB-INF/views/output/file/file.jsp
  src/main/webapp/WEB-INF/views/output/modal/file-insert-modal.jsp
  src/main/webapp/WEB-INF/views/test/test.jsp
  src/main/webapp/resources/defect/css/defect.css
  src/main/webapp/resources/defect/css/list.css
  src/main/webapp/resources/defect/js/defect.js
  src/main/webapp/resources/defect/js/list.js
  src/main/webapp/resources/member/js/teamMemberRegister.js
  src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
  src/main/webapp/resources/output/js/list.js
  src/main/webapp/resources/test/css/test.css
  src/main/webapp/resources/test/js/test.js
Labels: refactor, fix

#236 [#234] 결함 에러 수정
  src/main/java/com/kcc/pms/domain/task/defect/mapper/DefectMapper.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
  src/main/java/com/kcc/pms/domain/test/service/TestServiceImpl.java
  src/main/resources/mapper/task/DefectMapper.xml
  src/main/webapp/WEB-INF/views/test/test.jsp
  src/main/webapp/resources/defect/css/list.css
  src/main/webapp/resources/defect/js/defect.js
  src/main/webapp/resources/test/css/test.css
  src/main/webapp/resources/test/js/test.js
Labels: refactor, fix

#238 [#231] 위험 조치이력 생성 및 수정
  src/main/java/com/kcc/pms/domain/risk/controller/RiskController.java
  src/main/java/com/kcc/pms/domain/risk/mapper/RiskMapper.java
  src/main/java/com/kcc/pms/domain/risk/model/dto/RiskFileRequestDto.java
  src/main/java/com/kcc/pms/domain/risk/model/dto/RiskHistoryDto.java
  src/main/java/com/kcc/pms/domain/risk/service/RiskService.java
  src/main/java/com/kcc/pms/domain/risk/service/RiskServiceImpl.java
  src/main/resources/mapper/task/RiskMapper.xml
  src/main/webapp/WEB-INF/views/danger/info.jsp
  src/main/webapp/resources/danger/js/info.js
  src/main/webapp/resources/issue/css/info.css
Labels: feature

#240 [#239] 위험첨부오류해결
  src/main/resources/data.sql
  src/main/webapp/resources/danger/js/info.js
Labels: feature

#244 [#243] 조치이력 수정,삭제 제한
  src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/java/com/kcc/pms/domain/risk/controller/RiskController.java
  src/main/java/com/kcc/pms/domain/risk/mapper/RiskMapper.java
  src/main/java/com/kcc/pms/domain/risk/service/RiskService.java
  src/main/java/com/kcc/pms/domain/risk/service/RiskServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/task/RiskMapper.xml
  src/main/webapp/WEB-INF/views/danger/info.jsp
  src/main/webapp/WEB-INF/views/header.jsp
  src/main/webapp/resources/danger/js/info.js
  src/main/webapp/resources/issue/css/info.css
Labels: feature

#245 [#234] 결함 저장 오류 개선
  src/main/webapp/WEB-INF/views/defect/defect.jsp
  src/main/webapp/resources/defect/css/defect.css
  src/main/webapp/resources/defect/js/defect.js
  src/main/webapp/resources/defect/js/list.js
Labels: refactor, fix

#247 [#246] 인력등록 팝업페이지 오류 수정
  src/main/webapp/resources/common/js/common.js
  src/main/webapp/resources/member/css/teamMemberRegister.css
  src/main/webapp/resources/member/js/teamMemberRegister.js
  src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
  src/main/webapp/resources/wbs/js/wbsInfo.js
Labels: fix

#248 [#237] 산출물 새 폴더 만들기 개선사항 적용
  src/main/java/com/kcc/pms/domain/output/controller/OutputController.java
  src/main/java/com/kcc/pms/domain/output/service/OutputService.java
  src/main/java/com/kcc/pms/domain/output/service/OutputServiceImpl.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
  src/main/resources/data.sql
  src/main/webapp/WEB-INF/views/output/modal/folder-modal.jsp
  src/main/webapp/resources/output/js/jstree.js
Labels: refactor, fix

#251 [#190] 작업자별 진척도 검색 및 조회 및 작업자 작업 목록 상세
  src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
  src/main/java/com/kcc/pms/domain/feature/mapper/FeatureMapper.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/FeatureMemberPrgResponseDto.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/GraphParams.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/MemberFeatGraphResponseDto.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/MemberFeatureDto.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/MemberFeaturesResponseDto.java
  src/main/java/com/kcc/pms/domain/feature/service/FeatureService.java
  src/main/java/com/kcc/pms/domain/feature/service/FeatureServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/FeatureMapper.xml
  src/main/webapp/WEB-INF/views/feature/list.jsp
  src/main/webapp/resources/feature/css/featureList.css
  src/main/webapp/resources/feature/js/featureInfo.js
  src/main/webapp/resources/feature/js/list.js
  src/main/webapp/resources/member/js/teamMemberRegister.js
  src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
Labels: feature

#250 [#249] 결함 도메인 개선사항 적용 및 더미 경로 제거
  src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
  src/main/java/com/kcc/pms/domain/common/model/dto/FileItem.java
  src/main/java/com/kcc/pms/domain/common/service/CommonServiceImpl.java
  src/main/java/com/kcc/pms/domain/common/util/AwsS3Utils.java
  src/main/java/com/kcc/pms/domain/output/controller/OutputController.java
  src/main/java/com/kcc/pms/domain/output/domain/dto/OutputFile.java
  src/main/java/com/kcc/pms/domain/output/domain/dto/OutputResponseDto.java
  src/main/java/com/kcc/pms/domain/output/mapper/OutputMapper.java
  src/main/java/com/kcc/pms/domain/output/service/OutputService.java
  src/main/java/com/kcc/pms/domain/output/service/OutputServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/mapper/OutputMapper.xml
  src/main/webapp/WEB-INF/views/output/file/file-task.jsp
  src/main/webapp/WEB-INF/views/output/file/file.jsp
  src/main/webapp/WEB-INF/views/output/list.jsp
  src/main/webapp/WEB-INF/views/output/modal/file-insert-modal.jsp
  src/main/webapp/WEB-INF/views/output/modal/output-file-insert.jsp
  src/main/webapp/WEB-INF/views/output/output-search.jsp
  src/main/webapp/resources/output/css/list.css
  src/main/webapp/resources/output/js/jstree.js
  src/main/webapp/resources/output/js/list.js
Labels: refactor, feature, fix

#254 [#229] 위험 관리 대장 액셀 다운로드
  pom.xml
  src/main/java/com/kcc/pms/domain/common/util/ExcelGenerator.java
  src/main/java/com/kcc/pms/domain/risk/controller/RiskController.java
  src/main/java/com/kcc/pms/domain/risk/mapper/RiskMapper.java
  src/main/java/com/kcc/pms/domain/risk/model/excel/ExcelFileDetailDto.java
  src/main/java/com/kcc/pms/domain/risk/model/excel/ExcelHistoryDto.java
  src/main/java/com/kcc/pms/domain/risk/model/excel/ExcelRiskDto.java
  src/main/java/com/kcc/pms/domain/risk/service/RiskService.java
  src/main/java/com/kcc/pms/domain/risk/service/RiskServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/task/RiskMapper.xml
  src/main/webapp/resources/danger/js/danger.js
Labels: feature

#257 [#256] 이슈 기능 완성
  src/main/java/com/kcc/pms/domain/common/util/IssueExcelGenerator.java
  src/main/java/com/kcc/pms/domain/risk/controller/RiskController.java
  src/main/java/com/kcc/pms/domain/risk/mapper/RiskMapper.java
  src/main/java/com/kcc/pms/domain/risk/model/dto/CriteriaRisk.java
  src/main/java/com/kcc/pms/domain/risk/model/dto/RiskDto.java
  src/main/java/com/kcc/pms/domain/risk/model/excel/ExcelRiskDto.java
  src/main/java/com/kcc/pms/domain/risk/service/RiskService.java
  src/main/java/com/kcc/pms/domain/risk/service/RiskServiceImpl.java
  src/main/java/com/kcc/pms/domain/task/issue/controller/IssueController.java
  src/main/resources/data.sql
  src/main/resources/mapper/task/RiskMapper.xml
  src/main/webapp/WEB-INF/views/issue/info.jsp
  src/main/webapp/WEB-INF/views/issue/list.jsp
  src/main/webapp/resources/danger/js/danger.js
  src/main/webapp/resources/danger/js/info.js
  src/main/webapp/resources/issue/js/info.js
  src/main/webapp/resources/issue/js/list.js
Labels: feature

#261 [#260] 투입인력팝업페이지 보완
  src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
  src/main/java/com/kcc/pms/domain/member/mapper/MemberMapper.java
  src/main/java/com/kcc/pms/domain/member/model/dto/MemberTeamUpdateRequest.java
  src/main/java/com/kcc/pms/domain/member/service/MemberService.java
  src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
  src/main/java/com/kcc/pms/domain/team/controller/TeamController.java
  src/main/java/com/kcc/pms/domain/team/model/dto/MemberAddRequestDto.java
  src/main/java/com/kcc/pms/domain/team/service/TeamService.java
  src/main/java/com/kcc/pms/domain/team/service/TeamServiceImpl.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/webapp/resources/member/js/memberRegisterGrid.js
Labels: refactor

#264 [#263] 테스트 결함 산출물 오류 수정
  src/main/java/com/kcc/pms/domain/member/service/MemberService.java
  src/main/java/com/kcc/pms/domain/output/service/OutputServiceImpl.java
  src/main/java/com/kcc/pms/domain/team/service/TeamServiceImpl.java
  src/main/java/com/kcc/pms/domain/test/service/TestServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/OutputMapper.xml
  src/main/resources/mapper/TestMapper.xml
  src/main/webapp/resources/common/js/common.js
  src/main/webapp/resources/test/js/test.js
Labels: fix

#267 [#266] refactor: 더미수정
  src/main/java/com/kcc/pms/domain/common/util/ExcelGenerator.java
  src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
  src/main/java/com/kcc/pms/domain/member/model/dto/GroupMembersResponseDto.java
  src/main/java/com/kcc/pms/domain/member/model/dto/MemberResponseDto.java
  src/main/java/com/kcc/pms/domain/member/service/MemberService.java
  src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/FeatureMapper.xml
  src/main/webapp/WEB-INF/views/danger/danger_list.jsp
  src/main/webapp/WEB-INF/views/feature/list.jsp
  src/main/webapp/WEB-INF/views/issue/list.jsp
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/WEB-INF/views/member/memberRegister.jsp
  src/main/webapp/resources/feature/js/list.js
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/member/css/memberRegister.css
  src/main/webapp/resources/member/js/list.js
  src/main/webapp/resources/member/js/memberRegister.js
  src/main/webapp/resources/member/js/memberRegisterGrid.js
  src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
Labels: refactor

#268 더미 데이터 병합
  pom.xml
  src/main/java/com/kcc/pms/domain/system/mapper/SystemMapper.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
  src/main/java/com/kcc/pms/domain/test/controller/TestController.java
  src/main/java/com/kcc/pms/domain/test/mapper/TestMapper.java
  src/main/java/com/kcc/pms/domain/test/service/TestService.java
  src/main/java/com/kcc/pms/domain/test/service/TestServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/mapper/SystemMapper.xml
  src/main/resources/mapper/TestMapper.xml
  src/main/resources/templates/unitTest.xlsx
  src/main/webapp/WEB-INF/views/defect/defect.jsp
  src/main/webapp/WEB-INF/views/output/output-search.jsp
  src/main/webapp/WEB-INF/views/test/test.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsList.jsp
  src/main/webapp/resources/defect/js/defect.js
  src/main/webapp/resources/test/css/list.css
  src/main/webapp/resources/test/css/test.css
  src/main/webapp/resources/test/js/test.js
  src/main/webapp/resources/wbs/css/wbsList.css
Labels: refactor, feature, fix

#270 운영 환경 코드 배포
  pom.xml
  src/main/java/com/kcc/pms/domain/common/util/ExcelGenerator.java
  src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
  src/main/java/com/kcc/pms/domain/member/model/dto/GroupMembersResponseDto.java
  src/main/java/com/kcc/pms/domain/member/model/dto/MemberResponseDto.java
  src/main/java/com/kcc/pms/domain/member/service/MemberService.java
  src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
  src/main/java/com/kcc/pms/domain/system/mapper/SystemMapper.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
  src/main/java/com/kcc/pms/domain/test/controller/TestController.java
  src/main/java/com/kcc/pms/domain/test/mapper/TestMapper.java
  src/main/java/com/kcc/pms/domain/test/service/TestService.java
  src/main/java/com/kcc/pms/domain/test/service/TestServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/mapper/FeatureMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/ProjectMapper.xml
  src/main/resources/mapper/SystemMapper.xml
  src/main/resources/mapper/TestMapper.xml
  src/main/resources/mapper/WbsMapper.xml
  src/main/resources/mapper/task/DefectMapper.xml
  src/main/resources/mapper/task/RiskMapper.xml
  src/main/resources/templates/unitTest.xlsx
  src/main/webapp/WEB-INF/views/danger/danger_list.jsp
  src/main/webapp/WEB-INF/views/defect/defect.jsp
  src/main/webapp/WEB-INF/views/feature/list.jsp
  src/main/webapp/WEB-INF/views/issue/list.jsp
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/WEB-INF/views/member/memberRegister.jsp
  src/main/webapp/WEB-INF/views/output/output-search.jsp
  src/main/webapp/WEB-INF/views/test/test.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsList.jsp
  src/main/webapp/resources/defect/js/defect.js
  src/main/webapp/resources/feature/js/list.js
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/member/css/memberRegister.css
  src/main/webapp/resources/member/js/list.js
  src/main/webapp/resources/member/js/memberRegister.js
  src/main/webapp/resources/member/js/memberRegisterGrid.js
  src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
  src/main/webapp/resources/test/css/list.css
  src/main/webapp/resources/test/css/test.css
  src/main/webapp/resources/test/js/test.js
  src/main/webapp/resources/wbs/css/wbsList.css
Labels: refactor, feature, fix

#271 fix 체크 개선
  src/main/java/com/kcc/pms/domain/test/service/TestServiceImpl.java
  src/main/resources/mapper/TestMapper.xml
Labels: refactor, fix

#273 [fix] to_date 개선
  src/main/resources/mapper/FeatureMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/task/DefectMapper.xml
  src/main/resources/mapper/task/RiskMapper.xml
  src/main/webapp/resources/feature/js/list.js
Labels: refactor, fix

#276 [#275] to_date_fix
  src/main/resources/mapper/ProjectMapper.xml
  src/main/resources/mapper/TestMapper.xml
  src/main/resources/mapper/WbsMapper.xml
Labels: fix

#274 운영환경 코드 적용
  src/main/resources/mapper/FeatureMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/ProjectMapper.xml
  src/main/resources/mapper/TestMapper.xml
  src/main/resources/mapper/WbsMapper.xml
  src/main/resources/mapper/task/DefectMapper.xml
  src/main/resources/mapper/task/RiskMapper.xml
Labels: refactor, fix
