Repository KCC-Team/KCC-PMS, pull requests merged in 2024-10, with the labels that each got.

#5 파일 경로 수정
  src/main/webapp/WEB-INF/views/common.jsp
  src/main/webapp/WEB-INF/views/footer.jsp
  src/main/webapp/WEB-INF/views/project/dashboard.jsp
  src/main/webapp/WEB-INF/views/project/info.jsp
  src/main/webapp/WEB-INF/views/project/list.jsp
  src/main/webapp/WEB-INF/views/project/modify.jsp
  src/main/webapp/WEB-INF/views/project/projectHeader.jsp
Labels: enhancement

#14 [#13] 프로젝트 yml 구성
  .gitignore
  src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
  src/main/resources/application-secret.yml.template
  src/main/resources/application.yml
Labels: refactor, setting

#18 위험 목록 UI 구현
  src/main/java/com/kcc/pms/domain/task/danger/controller/DangerController.java
  src/main/webapp/WEB-INF/views/common.jsp
  src/main/webapp/WEB-INF/views/danger/danger_list.jsp
  src/main/webapp/resources/danger/css/ax5grid.css
  src/main/webapp/resources/danger/css/danger.css
  src/main/webapp/resources/danger/js/danger.js
Labels: feature

#23 투입 인력 관리 UI 작업
  src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/member/js/list.js
Labels: feature

#25 [#15] 산출물 관리 UI 구현
  pom.xml
  src/main/java/com/kcc/pms/domain/output/controller/OutputController.java
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/webapp/WEB-INF/views/header.jsp
  src/main/webapp/WEB-INF/views/output/list.jsp
  src/main/webapp/resources/output/css/ax5grid.css
  src/main/webapp/resources/output/css/list.css
  src/main/webapp/resources/output/images/edit.png
  src/main/webapp/resources/output/js/list.js
Labels: feature, setting

#26 [#15] 산출물 관리 UI 구현
  pom.xml
  src/main/webapp/WEB-INF/views/output/list.jsp
  src/main/webapp/resources/common/css/common.css
  src/main/webapp/resources/output/css/list.css
  src/main/webapp/resources/output/js/list.js
Labels: refactor, feature

#27 [#noissue] \
  src/main/webapp/WEB-INF/views/common.jsp
  src/main/webapp/WEB-INF/views/output/list.jsp
  src/main/webapp/WEB-INF/views/project/projectHeader.jsp
  src/main/webapp/resources/common/images/main_logo.png
Labels: refactor

#29 [#28] 산출물 파일 상세 조회 로직 구현
  src/main/webapp/WEB-INF/views/output/file-detail-modal.jsp
  src/main/webapp/WEB-INF/views/output/list.jsp
  src/main/webapp/resources/output/css/ax5grid.css
  src/main/webapp/resources/output/css/list.css
  src/main/webapp/resources/output/js/list.js
Labels: refactor, feature

#30 feat: 인력등록팝업화면구현(8)
  src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
  src/main/webapp/WEB-INF/views/common.jsp
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/WEB-INF/views/member/memberRegister.jsp
  src/main/webapp/resources/member/css/ax5grid.css
  src/main/webapp/resources/member/css/memberRegister.css
  src/main/webapp/resources/member/js/list.js
  src/main/webapp/resources/member/js/memberRegister.js
  src/main/webapp/resources/member/js/memberRegisterGrid.js
Labels: feature

#32 [#24] WBS UI 구현
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/java/com/kcc/pms/domain/project/controller/WbsController.java
  src/main/webapp/WEB-INF/views/project/wbsList.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsList.jsp
  src/main/webapp/resources/project/css/wbsList.css
  src/main/webapp/resources/wbs/css/wbsInfo.css
  src/main/webapp/resources/wbs/css/wbsList.css
  src/main/webapp/resources/wbs/js/wbsInfo.js
  src/main/webapp/resources/wbs/js/wbsList.js
Labels: feature

#38 dto명 변경
  src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
  src/main/java/com/kcc/pms/domain/common/mapper/CommonMapper.java
  src/main/java/com/kcc/pms/domain/common/model/dto/CommonCodeSelectListResponseDto.java
  src/main/java/com/kcc/pms/domain/common/service/CommonService.java
  src/main/java/com/kcc/pms/domain/common/service/CommonServiceImpl.java
  src/main/resources/mapper/CommonMapper.xml
Labels: fix

#40 [#39] 권한목록 조회 서버,화면 로직 구현
  src/main/webapp/resources/member/js/memberRegisterGrid.js
Labels: feature

#42 [#41] 트리구조로 조직도 조회 서버 로직 구현
  src/main/java/com/kcc/pms/domain/common/model/dto/CommonCodeSelectListResponseDto.java
  src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
  src/main/java/com/kcc/pms/domain/member/mapper/MemberMapper.java
  src/main/java/com/kcc/pms/domain/member/model/dto/GroupResponseDto.java
  src/main/java/com/kcc/pms/domain/member/service/MemberService.java
  src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/webapp/resources/member/js/memberRegister.js
Labels: feature

#47 [#35] 산출물 도메인 새 폴더 생성 클라이언트 모달 및 로직 구현 등
  src/main/webapp/WEB-INF/views/common.jsp
  src/main/webapp/WEB-INF/views/output/file/file.jsp
  src/main/webapp/WEB-INF/views/output/jstree-folder.jsp
  src/main/webapp/WEB-INF/views/output/jstree.jsp
  src/main/webapp/WEB-INF/views/output/list.jsp
  src/main/webapp/WEB-INF/views/output/modal/file-insert-modal.jsp
  src/main/webapp/WEB-INF/views/output/modal/folder-modal.jsp
  src/main/webapp/WEB-INF/views/output/modal/output-file-insert.jsp
  src/main/webapp/WEB-INF/views/output/modal/output-file-reinsert.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsList.jsp
  src/main/webapp/resources/output/images/file-icon.png
  src/main/webapp/resources/output/js/jstree.js
  src/main/webapp/resources/output/js/list.js
Labels: refactor, feature

#49 [#46] 인력관리 화면 UI 개선
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/member/js/list.js
Labels: refactor

#50 #[33] 프로젝트 등록 작업
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
  src/main/java/com/kcc/pms/domain/project/model/dto/ProjectDto.java
  src/main/java/com/kcc/pms/domain/project/model/vo/ProjectMemberVO.java
  src/main/java/com/kcc/pms/domain/project/model/vo/ProjectVO.java
  src/main/java/com/kcc/pms/domain/project/model/vo/TeamVO.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectService.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
  src/main/resources/mapper/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/header.jsp
  src/main/webapp/WEB-INF/views/project/info.jsp
  src/main/webapp/WEB-INF/views/project/list.jsp
  src/main/webapp/WEB-INF/views/project/projectHeader.jsp
  src/main/webapp/WEB-INF/views/project/register.jsp
  src/main/webapp/resources/member/js/memberRegisterGrid.js
  src/main/webapp/resources/project/css/list.css
  src/main/webapp/resources/project/css/modify.css
  src/main/webapp/resources/project/css/register.css
  src/main/webapp/resources/project/js/info.js
  src/main/webapp/resources/project/js/list.js
  src/main/webapp/resources/project/js/modify.js
  src/main/webapp/resources/project/js/register.js
Labels: feature

#52 #[51] 프로젝트 조회 작업
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
  src/main/java/com/kcc/pms/domain/project/model/dto/ProjectManagerResponseDto.java
  src/main/java/com/kcc/pms/domain/project/model/dto/ProjectRequestDto.java
  src/main/java/com/kcc/pms/domain/project/model/dto/ProjectResponseDto.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectService.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
  src/main/resources/mapper/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/common.jsp
  src/main/webapp/WEB-INF/views/project/dashboard.jsp
  src/main/webapp/WEB-INF/views/project/list.jsp
  src/main/webapp/resources/member/js/memberRegisterGrid.js
Labels: feature

#53 [#45] 프로젝트 팀 목록 조회 및 팀 상세 조회
  src/main/java/com/kcc/pms/domain/team/controller/TeamController.java
  src/main/java/com/kcc/pms/domain/team/mapper/TeamMapper.java
  src/main/java/com/kcc/pms/domain/team/model/dto/TeamMemberResponseDto.java
  src/main/java/com/kcc/pms/domain/team/model/dto/TeamResponseDto.java
  src/main/java/com/kcc/pms/domain/team/model/vo/Team.java
  src/main/java/com/kcc/pms/domain/team/service/TeamService.java
  src/main/java/com/kcc/pms/domain/team/service/TeamServiceImpl.java
  src/main/resources/mapper/TeamMapper.xml
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/member/js/list.js
Labels: feature

#54 [#48] 테스트 관리 카테고리에 대한 UI를 구현
  src/main/java/com/kcc/pms/domain/test/controller/TestController.java
  src/main/webapp/WEB-INF/views/common.jsp
  src/main/webapp/WEB-INF/views/output/jstree-folder.jsp
  src/main/webapp/WEB-INF/views/output/list.jsp
  src/main/webapp/WEB-INF/views/output/modal/file-insert-modal.jsp
  src/main/webapp/WEB-INF/views/test/list.jsp
  src/main/webapp/WEB-INF/views/test/test.jsp
  src/main/webapp/resources/common/css/common.css
  src/main/webapp/resources/output/css/list.css
  src/main/webapp/resources/output/js/jstree.js
  src/main/webapp/resources/output/js/list.js
  src/main/webapp/resources/test/css/ax5grid.css
  src/main/webapp/resources/test/css/list.css
  src/main/webapp/resources/test/css/test.css
  src/main/webapp/resources/test/js/list.js
  src/main/webapp/resources/test/js/test.js
Labels: refactor, feature

#57 #[51] 프로젝트 조회 작업
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
  src/main/java/com/kcc/pms/domain/project/model/dto/Criteria.java
  src/main/java/com/kcc/pms/domain/project/model/dto/PageDto.java
  src/main/java/com/kcc/pms/domain/project/model/dto/ProjectRequestDto.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectService.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
  src/main/resources/mapper/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/project/info.jsp
  src/main/webapp/WEB-INF/views/project/list.jsp
  src/main/webapp/resources/project/css/list.css
  src/main/webapp/resources/project/css/register.css
  src/main/webapp/resources/project/js/info.js
  src/main/webapp/resources/project/js/list.js
Labels: feature

#62 [#56] 프로젝트 총인원 목록 조회 서버 로직 구현
  src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
  src/main/java/com/kcc/pms/domain/member/mapper/MemberMapper.java
  src/main/java/com/kcc/pms/domain/member/model/dto/GroupMembersResponseDto.java
  src/main/java/com/kcc/pms/domain/member/model/dto/MemberResponseDto.java
  src/main/java/com/kcc/pms/domain/member/model/dto/ProjectMemberResponseDto.java
  src/main/java/com/kcc/pms/domain/member/service/MemberService.java
  src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
  src/main/java/com/kcc/pms/domain/team/controller/TeamController.java
  src/main/java/com/kcc/pms/domain/team/mapper/TeamMapper.java
  src/main/java/com/kcc/pms/domain/team/model/dto/TeamResponseDto.java
  src/main/java/com/kcc/pms/domain/team/service/TeamService.java
  src/main/java/com/kcc/pms/domain/team/service/TeamServiceImpl.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/TeamMapper.xml
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/member/js/list.js
  src/main/webapp/resources/member/js/memberRegister.js
  src/main/webapp/resources/member/js/memberRegisterGrid.js
Labels: feature

#66 [#58] 프로젝트 수정 구현
  src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
  src/main/java/com/kcc/pms/domain/project/model/dto/CombinedProjectResponseDto.java
  src/main/java/com/kcc/pms/domain/project/model/dto/ProjectRequestDto.java
  src/main/java/com/kcc/pms/domain/project/model/dto/ProjectResponseDto.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectService.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
  src/main/resources/mapper/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/header.jsp
  src/main/webapp/WEB-INF/views/project/dashboard.jsp
  src/main/webapp/WEB-INF/views/project/info.jsp
  src/main/webapp/WEB-INF/views/project/list.jsp
  src/main/webapp/resources/common/js/common.js
  src/main/webapp/resources/project/css/info.css
  src/main/webapp/resources/project/css/list.css
  src/main/webapp/resources/project/css/register.css
  src/main/webapp/resources/project/js/info.js
  src/main/webapp/resources/project/js/list.js
Labels: feature

#67 [#63] 팀 트리 구조 순서 변경 서버 로직 구현
  src/main/java/com/kcc/pms/domain/team/controller/TeamController.java
  src/main/java/com/kcc/pms/domain/team/mapper/TeamMapper.java
  src/main/java/com/kcc/pms/domain/team/model/dto/TeamOrderUpdateRequestDto.java
  src/main/java/com/kcc/pms/domain/team/model/vo/Team.java
  src/main/java/com/kcc/pms/domain/team/service/TeamService.java
  src/main/java/com/kcc/pms/domain/team/service/TeamServiceImpl.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/TeamMapper.xml
  src/main/webapp/resources/member/js/list.js
Labels: feature

#68 [#64] 팀 생성 화면 구현
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/member/js/list.js
Labels: feature

#73 [#72] 팀 등록 디자인 변경
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/member/js/list.js
Labels: refactor

#74 [#70] 이슈 / 위험 / 프로젝트 레이아웃 수정
  src/main/webapp/WEB-INF/views/danger/danger_list.jsp
  src/main/webapp/WEB-INF/views/danger/info.jsp
  src/main/webapp/WEB-INF/views/issue/info.jsp
  src/main/webapp/WEB-INF/views/issue/list.jsp
  src/main/webapp/resources/danger/css/ax5grid.css
  src/main/webapp/resources/danger/js/danger.js
  src/main/webapp/resources/danger/js/info.js
  src/main/webapp/resources/issue/css/info.css
  src/main/webapp/resources/issue/js/info.js
  src/main/webapp/resources/issue/js/list.js
  src/main/webapp/resources/project/css/info.css
  src/main/webapp/resources/project/css/register.css
Labels: refactor

#75 [#61] 테스트 목록 API 구현 중간 적용 및 설정 적용
  pom.xml
  src/main/java/com/kcc/pms/domain/task/defect/controller/DefectController.java
  src/main/java/com/kcc/pms/domain/test/controller/TestController.java
  src/main/java/com/kcc/pms/domain/test/domain/dto/TestListResponseDto.java
  src/main/java/com/kcc/pms/domain/test/mapper/TestMapper.java
  src/main/java/com/kcc/pms/domain/test/service/TestService.java
  src/main/java/com/kcc/pms/domain/test/service/TestServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/TestMapper.xml
  src/main/webapp/WEB-INF/views/common.jsp
  src/main/webapp/WEB-INF/views/defect/list.jsp
  src/main/webapp/WEB-INF/views/output/list.jsp
  src/main/webapp/WEB-INF/views/test/list.jsp
  src/main/webapp/resources/test/css/list.css
  src/main/webapp/resources/test/js/list.js
Labels: docs, refactor, feature

#76 [#65] 팀 생성 서버 로직 구현
  src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
  src/main/java/com/kcc/pms/domain/system/controller/SystemController.java
  src/main/java/com/kcc/pms/domain/system/mapper/SystemMapper.java
  src/main/java/com/kcc/pms/domain/system/model/dto/SystemResponseDTO.java
  src/main/java/com/kcc/pms/domain/system/service/SystemService.java
  src/main/java/com/kcc/pms/domain/system/service/SystemServiceImpl.java
  src/main/java/com/kcc/pms/domain/team/controller/TeamController.java
  src/main/java/com/kcc/pms/domain/team/mapper/TeamMapper.java
  src/main/java/com/kcc/pms/domain/team/model/dto/TeamRequestDto.java
  src/main/java/com/kcc/pms/domain/team/model/vo/Team.java
  src/main/java/com/kcc/pms/domain/team/service/TeamService.java
  src/main/java/com/kcc/pms/domain/team/service/TeamServiceImpl.java
  src/main/resources/mapper/SystemMapper.xml
  src/main/resources/mapper/TeamMapper.xml
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/member/js/list.js
Labels: feature

#79 [#69] 프로젝트, WBS, 이슈, 위험 레이아웃 수정
  src/main/java/com/kcc/pms/domain/project/controller/WbsController.java
  src/main/resources/data.sql
  src/main/resources/mapper/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/header.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsList.jsp
  src/main/webapp/resources/danger/js/danger.js
  src/main/webapp/resources/issue/js/list.js
  src/main/webapp/resources/project/js/info.js
  src/main/webapp/resources/wbs/css/wbsInfo.css
  src/main/webapp/resources/wbs/css/wbsList.css
  src/main/webapp/resources/wbs/js/wbsList.js
Labels: refactor

#81 [#77] 사원 팀 배정 드래그 앤 드롭 구현
  src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
  src/main/java/com/kcc/pms/domain/member/mapper/MemberMapper.java
  src/main/java/com/kcc/pms/domain/member/model/dto/ProjectMemberResponseDto.java
  src/main/java/com/kcc/pms/domain/member/service/MemberService.java
  src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/TeamMapper.xml
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/member/js/list.js
Labels: feature

#83 [#80] 프로젝트 WBS 레이아웃 구현
  src/main/resources/mapper/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/member/memberRegister.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
  src/main/webapp/resources/member/js/memberRegisterGrid.js
  src/main/webapp/resources/project/js/info.js
  src/main/webapp/resources/wbs/css/wbsInfo.css
  src/main/webapp/resources/wbs/js/wbsInfo.js
  src/main/webapp/resources/wbs/js/wbsList.js
Labels: feature

#86 [#85] 프로젝트 update 수정
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/mapper/ProjectMapper.xml
Labels: refactor

#90 [#87] api경로 수정 및 인력,프로젝트 병합, 무소속 팀원 처리
  src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
  src/main/java/com/kcc/pms/domain/member/mapper/MemberMapper.java
  src/main/java/com/kcc/pms/domain/member/service/MemberService.java
  src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
  src/main/resources/mapper/MemberMapper.xml
  src/main/webapp/WEB-INF/views/member/memberRegister.jsp
  src/main/webapp/resources/member/js/list.js
  src/main/webapp/resources/member/js/memberRegisterGrid.js
Labels: refactor

#89 [#80] 프로젝트 WBS 등록 구현
  src/main/java/com/kcc/pms/domain/project/controller/WbsController.java
  src/main/java/com/kcc/pms/domain/wbs/controller/WbsController.java
  src/main/java/com/kcc/pms/domain/wbs/mapper/WbsMapper.java
  src/main/java/com/kcc/pms/domain/wbs/model/dto/WbsRequestDto.java
  src/main/java/com/kcc/pms/domain/wbs/model/dto/WbsResponseDto.java
  src/main/java/com/kcc/pms/domain/wbs/service/WbsService.java
  src/main/java/com/kcc/pms/domain/wbs/service/WbsServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/WbsMapper.xml
  src/main/webapp/WEB-INF/views/common.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsList.jsp
  src/main/webapp/resources/wbs/css/wbsList.css
  src/main/webapp/resources/wbs/js/wbsInfo.js
  src/main/webapp/resources/wbs/js/wbsList.js
Labels: feature

#96 [#61] 테스트 도메인 API 로직을 구현한다.
  src/main/java/com/kcc/pms/domain/test/controller/TestController.java
  src/main/java/com/kcc/pms/domain/test/domain/dto/TestDetailRequestDto.java
  src/main/java/com/kcc/pms/domain/test/domain/dto/TestListResponseDto.java
  src/main/java/com/kcc/pms/domain/test/domain/dto/TestRequestDto.java
  src/main/java/com/kcc/pms/domain/test/domain/dto/TestVO.java
  src/main/java/com/kcc/pms/domain/test/mapper/TestMapper.java
  src/main/java/com/kcc/pms/domain/test/service/TestService.java
  src/main/java/com/kcc/pms/domain/test/service/TestServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/TestMapper.xml
  src/main/webapp/WEB-INF/views/test/test.jsp
  src/main/webapp/resources/common/css/common.css
  src/main/webapp/resources/test/css/test.css
  src/main/webapp/resources/test/js/list.js
  src/main/webapp/resources/test/js/test.js
Labels: refactor, feature, fix

#97 [#noissue] 더미데이터 최신화
  src/main/resources/data.sql
Labels: refactor

#98 [#91] 프로젝트명 세션 수정, 프로젝트 팀원 목록 수정
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
  src/main/java/com/kcc/pms/domain/wbs/service/WbsServiceImpl.java
  src/main/resources/mapper/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/header.jsp
  src/main/webapp/resources/common/js/common.js
  src/main/webapp/resources/member/js/memberRegisterGrid.js
  src/main/webapp/resources/project/js/info.js
  src/main/webapp/resources/wbs/js/wbsInfo.js
  src/main/webapp/resources/wbs/js/wbsList.js
Labels: refactor

#100 [#noissue] 더미데이터 최신화
  src/main/resources/data.sql
Labels: refactor

#101 [#99]프로젝트 WBS 등록 구현 / 하위 작업 구현
  src/main/webapp/WEB-INF/views/project/dashboard.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/project/css/dashboard.css
  src/main/webapp/resources/wbs/js/wbsInfo.js
  src/main/webapp/resources/wbs/js/wbsList.js
Labels: feature

#102 프로젝트 검색 에러 수정
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/webapp/WEB-INF/views/danger/danger_list.jsp
  src/main/webapp/WEB-INF/views/header.jsp
  src/main/webapp/WEB-INF/views/issue/list.jsp
  src/main/webapp/resources/common/js/common.js
  src/main/webapp/resources/danger/css/danger.css
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/project/css/info.css
Labels: bug

#104 [#95] 위험등록 공통코드 가져오는 로직 구현
  .gitignore
  src/main/java/com/kcc/pms/domain/risk/controller/RiskController.java
  src/main/java/com/kcc/pms/domain/risk/mapper/RiskMapper.java
  src/main/java/com/kcc/pms/domain/risk/model/dto/RiskCeateRequestDto.java
  src/main/java/com/kcc/pms/domain/risk/model/dto/RiskCommonCodeOptions.java
  src/main/java/com/kcc/pms/domain/risk/model/vo/CommonCodeVO.java
  src/main/java/com/kcc/pms/domain/risk/service/RiskService.java
  src/main/java/com/kcc/pms/domain/risk/service/RiskServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/RiskMapper.xml
  src/main/webapp/WEB-INF/views/danger/info.jsp
  src/main/webapp/WEB-INF/views/header.jsp
  src/main/webapp/WEB-INF/views/output/file/file.jsp
  src/main/webapp/resources/danger/js/info.js
  src/main/webapp/resources/issue/css/info.css
Labels: feature

#105 [#103] 전체 레이아웃 디자인 수정
  src/main/webapp/WEB-INF/views/danger/danger_list.jsp
  src/main/webapp/WEB-INF/views/defect/list.jsp
  src/main/webapp/WEB-INF/views/issue/list.jsp
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/WEB-INF/views/member/memberRegister.jsp
  src/main/webapp/WEB-INF/views/output/list.jsp
  src/main/webapp/WEB-INF/views/test/list.jsp
  src/main/webapp/WEB-INF/views/test/test.jsp
  src/main/webapp/resources/common/css/ax5grid.css
  src/main/webapp/resources/common/css/ax5gridMin.css
  src/main/webapp/resources/danger/css/ax5grid.css
  src/main/webapp/resources/danger/css/danger.css
  src/main/webapp/resources/danger/js/danger.js
  src/main/webapp/resources/issue/js/list.js
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/output/css/ax5grid.css
  src/main/webapp/resources/project/css/info.css
  src/main/webapp/resources/project/css/list.css
  src/main/webapp/resources/test/css/ax5grid.css
Labels: refactor

#110 [#109] 위험 이슈 레이아웃 재설정
  src/main/webapp/WEB-INF/views/danger/danger_list.jsp
  src/main/webapp/WEB-INF/views/issue/list.jsp
  src/main/webapp/resources/danger/js/danger.js
  src/main/webapp/resources/issue/js/list.js
Labels: refactor

#111 [#106] 결함 레이아웃 수정
  src/main/java/com/kcc/pms/domain/output/controller/OutputController.java
  src/main/webapp/WEB-INF/views/defect/list.jsp
  src/main/webapp/resources/common/css/common.css
  src/main/webapp/resources/danger/css/danger.css
  src/main/webapp/resources/defect/js/list.js
Labels: refactor

#114 [#113] 투입인력 페이지 레이아웃 재설정
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/member/js/list.js
Labels: refactor, feature

#116 [#108] 기능 등록 UI 구현
  src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
  src/main/webapp/WEB-INF/views/common.jsp
  src/main/webapp/WEB-INF/views/feature/featureInfo.jsp
  src/main/webapp/WEB-INF/views/feature/list.jsp
  src/main/webapp/resources/feature/css/featureInfo.css
  src/main/webapp/resources/feature/js/list.js
Labels: feature

#118 [#112] 산출물 관리 레이아웃 수정
  src/main/java/com/kcc/pms/domain/output/controller/OutputController.java
  src/main/webapp/WEB-INF/views/output/jstree-folder.jsp
  src/main/webapp/WEB-INF/views/output/list.jsp
  src/main/webapp/WEB-INF/views/output/modal/file-detail-modal.jsp
  src/main/webapp/WEB-INF/views/output/modal/file-history-modal.jsp
  src/main/webapp/WEB-INF/views/output/modal/file-insert-modal.jsp
  src/main/webapp/WEB-INF/views/output/modal/folder-modal.jsp
  src/main/webapp/WEB-INF/views/output/modal/output-file-insert.jsp
  src/main/webapp/WEB-INF/views/output/modal/output-file-reinsert.jsp
  src/main/webapp/resources/common/css/common.css
  src/main/webapp/resources/output/css/list.css
  src/main/webapp/resources/output/js/jstree.js
  src/main/webapp/resources/output/js/list.js
Labels: refactor

#122 [#107] 프로젝트 WBS 등록 구현
  src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectService.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
  src/main/webapp/WEB-INF/views/header.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
  src/main/webapp/resources/project/css/register.css
  src/main/webapp/resources/wbs/css/wbsInfo.css
  src/main/webapp/resources/wbs/css/wbsList.css
  src/main/webapp/resources/wbs/js/wbsInfo.js
  src/main/webapp/resources/wbs/js/wbsList.js
Labels: feature

#125 [#123] WBS순서변경 서버로직 구현
  src/main/java/com/kcc/pms/domain/wbs/controller/WbsController.java
  src/main/java/com/kcc/pms/domain/wbs/mapper/WbsMapper.java
  src/main/java/com/kcc/pms/domain/wbs/model/dto/WbsOrderUpdateRequestDto.java
  src/main/java/com/kcc/pms/domain/wbs/model/dto/WbsRequestDto.java
  src/main/java/com/kcc/pms/domain/wbs/model/vo/Wbs.java
  src/main/java/com/kcc/pms/domain/wbs/service/WbsService.java
  src/main/java/com/kcc/pms/domain/wbs/service/WbsServiceImpl.java
  src/main/resources/mapper/WbsMapper.xml
  src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
  src/main/webapp/resources/wbs/js/wbsInfo.js
  src/main/webapp/resources/wbs/js/wbsList.js
Labels: feature

#129 [#128] 파일 업로드 API 구현
  pom.xml
  src/main/java/com/kcc/pms/domain/common/config/AwsS3Config.java
  src/main/java/com/kcc/pms/domain/common/config/EnvVariableProperties.java
  src/main/java/com/kcc/pms/domain/common/config/ProperTiesConfig.java
  src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
  src/main/java/com/kcc/pms/domain/common/service/CommonService.java
  src/main/java/com/kcc/pms/domain/common/service/CommonServiceImpl.java
  src/main/java/com/kcc/pms/domain/common/util/AwsS3Utils.java
  src/main/java/com/kcc/pms/domain/output/controller/OutputController.java
  src/main/java/com/kcc/pms/domain/output/domain/dto/FileStructResponseDto.java
  src/main/java/com/kcc/pms/domain/output/domain/vo/FileMasterVO.java
  src/main/java/com/kcc/pms/domain/output/mapper/FileMapper.java
  src/main/java/com/kcc/pms/domain/output/mapper/OutputMapper.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/mapper/FileMapper.xml
  src/main/webapp/WEB-INF/views/output/file/file.jsp
  src/main/webapp/WEB-INF/views/output/modal/file-insert-modal.jsp
  src/main/webapp/WEB-INF/views/output/modal/folder-modal.jsp
  src/main/webapp/resources/output/js/jstree.js
Labels: refactor, feature, setting

#133 [#131] WBS정보, 기능정보 팝업 레이아웃 수정
  src/main/webapp/WEB-INF/views/member/memberRegister.jsp
  src/main/webapp/resources/feature/css/featureInfo.css
  src/main/webapp/resources/feature/js/list.js
  src/main/webapp/resources/member/css/memberRegister.css
  src/main/webapp/resources/member/js/memberRegisterGrid.js
  src/main/webapp/resources/wbs/css/wbsInfo.css
  src/main/webapp/resources/wbs/js/wbsList.js
Labels: refactor

#134 [#132] 팀 트리 생성
  src/main/java/com/kcc/pms/domain/team/controller/TeamController.java
  src/main/java/com/kcc/pms/domain/team/mapper/TeamMapper.java
  src/main/java/com/kcc/pms/domain/team/model/dto/TeamResponseDto.java
  src/main/java/com/kcc/pms/domain/team/model/dto/TeamTreeResponseDto.java
  src/main/java/com/kcc/pms/domain/team/model/dto/TreeNode.java
  src/main/java/com/kcc/pms/domain/team/service/TeamService.java
  src/main/java/com/kcc/pms/domain/team/service/TeamServiceImpl.java
  src/main/resources/mapper/TeamMapper.xml
  src/main/webapp/WEB-INF/views/member/teamMemberRegister.jsp
  src/main/webapp/resources/member/js/teamMemberRegister.js
Labels: feature

#136 [#121] 팀 트리 구조 인력 선택 팝업
  src/main/java/com/kcc/pms/domain/member/controller/MemberController.java
  src/main/java/com/kcc/pms/domain/member/mapper/MemberMapper.java
  src/main/java/com/kcc/pms/domain/member/model/dto/ProjectMemberResponseDto.java
  src/main/java/com/kcc/pms/domain/member/service/MemberService.java
  src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
  src/main/java/com/kcc/pms/domain/team/controller/TeamController.java
  src/main/java/com/kcc/pms/domain/team/model/dto/TeamMemberResponseDto.java
  src/main/java/com/kcc/pms/domain/team/service/TeamService.java
  src/main/java/com/kcc/pms/domain/team/service/TeamServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mapper/MemberMapper.xml
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/WEB-INF/views/member/teamMemberRegister.jsp
  src/main/webapp/resources/member/css/memberRegister.css
  src/main/webapp/resources/member/js/list.js
  src/main/webapp/resources/member/js/teamMemberRegister.js
  src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
Labels: feature

#139 [#137] 팀 트리 구조 인력 등록 팝업 수정
  src/main/webapp/WEB-INF/views/member/teamMemberRegister.jsp
  src/main/webapp/resources/common/js/common.js
  src/main/webapp/resources/member/css/memberRegister.css
  src/main/webapp/resources/member/css/teamMemberRegister.css
  src/main/webapp/resources/member/js/list.js
  src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
Labels: refactor

#141 [#138] 결함 등록 API 중간 적용
  src/main/java/com/kcc/pms/domain/common/service/CommonService.java
  src/main/java/com/kcc/pms/domain/common/service/CommonServiceImpl.java
  src/main/java/com/kcc/pms/domain/task/defect/controller/DefectController.java
  src/main/java/com/kcc/pms/domain/task/defect/domain/dto/DefectRequestDto.java
  src/main/java/com/kcc/pms/domain/task/defect/mapper/DefectMapper.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectService.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
  src/main/resources/mapper/CommonMapper.xml
  src/main/resources/mapper/DefectMapper.xml
  src/main/webapp/WEB-INF/views/defect/defect.jsp
  src/main/webapp/WEB-INF/views/defect/list.jsp
  src/main/webapp/WEB-INF/views/output/file/file-task.jsp
  src/main/webapp/resources/common/css/common.css
  src/main/webapp/resources/defect/css/defect.css
  src/main/webapp/resources/defect/css/list.css
  src/main/webapp/resources/defect/js/defect.js
  src/main/webapp/resources/defect/js/list.js
Labels: refactor, feature

#142 [#138] 결함 등록 로직 중간 적용
  src/main/java/com/kcc/pms/domain/common/util/AwsS3Utils.java
  src/main/java/com/kcc/pms/domain/task/defect/controller/DefectController.java
  src/main/java/com/kcc/pms/domain/task/defect/domain/dto/DefectFileRequestDto.java
  src/main/java/com/kcc/pms/domain/task/defect/domain/dto/DefectRequestDto.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectService.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/DefectMapper.xml
  src/main/webapp/WEB-INF/views/defect/defect.jsp
  src/main/webapp/resources/defect/css/defect.css
  src/main/webapp/resources/defect/js/defect.js
Labels: refactor, feature

#143 [#130] 이슈 / 위험 레이아웃 수정 , 프로젝트 WBS 수정 / 상세 구현
  src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/java/com/kcc/pms/domain/wbs/controller/WbsController.java
  src/main/java/com/kcc/pms/domain/wbs/mapper/WbsMapper.java
  src/main/java/com/kcc/pms/domain/wbs/model/dto/WbsResponseDto.java
  src/main/java/com/kcc/pms/domain/wbs/service/WbsService.java
  src/main/java/com/kcc/pms/domain/wbs/service/WbsServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/WbsMapper.xml
  src/main/webapp/WEB-INF/views/danger/info.jsp
  src/main/webapp/WEB-INF/views/issue/info.jsp
  src/main/webapp/WEB-INF/views/member/memberRegister.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
  src/main/webapp/resources/danger/css/danger.css
  src/main/webapp/resources/danger/js/info.js
  src/main/webapp/resources/issue/css/info.css
  src/main/webapp/resources/member/js/memberRegisterGrid.js
  src/main/webapp/resources/project/js/info.js
  src/main/webapp/resources/wbs/css/wbsInfo.css
  src/main/webapp/resources/wbs/css/wbsList.css
  src/main/webapp/resources/wbs/js/wbsInfo.js
  src/main/webapp/resources/wbs/js/wbsList.js
Labels: refactor, feature

#144 [#140] 기능 생성 로직 구현
  src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
  src/main/java/com/kcc/pms/domain/feature/mapper/FeatureMapper.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/FeatureCreateRequestDto.java
  src/main/java/com/kcc/pms/domain/feature/service/FeatureService.java
  src/main/java/com/kcc/pms/domain/feature/service/FeatureServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/mapper/FeatureMapper.xml
  src/main/webapp/WEB-INF/views/feature/featureInfo.jsp
  src/main/webapp/WEB-INF/views/member/teamMemberRegister.jsp
  src/main/webapp/resources/common/js/common.js
  src/main/webapp/resources/feature/css/featureInfo.css
  src/main/webapp/resources/feature/js/featureInfo.js
  src/main/webapp/resources/member/css/teamMemberRegister.css
  src/main/webapp/resources/member/js/teamMemberRegister.js
  src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
Labels: feature

#147 [#138] 결함 등록 API 구현
  src/main/java/com/kcc/pms/domain/common/service/CommonServiceImpl.java
  src/main/java/com/kcc/pms/domain/output/domain/vo/FileMasterVO.java
  src/main/java/com/kcc/pms/domain/task/defect/controller/DefectController.java
  src/main/java/com/kcc/pms/domain/task/defect/domain/dto/DefectDto.java
  src/main/java/com/kcc/pms/domain/task/defect/domain/dto/DefectFileRequestDto.java
  src/main/java/com/kcc/pms/domain/task/defect/domain/dto/DefectRequestDto.java
  src/main/java/com/kcc/pms/domain/task/defect/mapper/DefectMapper.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectService.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
  src/main/java/com/kcc/pms/domain/test/controller/TestController.java
  src/main/java/com/kcc/pms/domain/test/domain/dto/TestDetailRequestDto.java
  src/main/java/com/kcc/pms/domain/test/domain/dto/TestDto.java
  src/main/java/com/kcc/pms/domain/test/domain/dto/TestRequestDto.java
  src/main/java/com/kcc/pms/domain/test/mapper/TestMapper.java
  src/main/java/com/kcc/pms/domain/test/service/TestService.java
  src/main/java/com/kcc/pms/domain/test/service/TestServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/DefectMapper.xml
  src/main/resources/mapper/FileMapper.xml
  src/main/resources/mapper/TestMapper.xml
  src/main/webapp/WEB-INF/views/defect/defect.jsp
  src/main/webapp/WEB-INF/views/test/test.jsp
  src/main/webapp/resources/defect/js/defect.js
Labels: refactor, feature

#149 [#145] 기능 등록 팝업 페이지 시스템/업무 선택박스 추가 및 줄임말 적용
  src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
  src/main/webapp/WEB-INF/views/feature/featureInfo.jsp
  src/main/webapp/resources/feature/css/featureInfo.css
  src/main/webapp/resources/feature/js/featureInfo.js
  src/main/webapp/resources/feature/js/list.js
Labels: fix

#150 [#146] 로그인 시큐리티 구현
  pom.xml
  src/main/java/com/kcc/pms/auth/PrincipalDetail.java
  src/main/java/com/kcc/pms/auth/PrincipalDetailService.java
  src/main/java/com/kcc/pms/auth/SecurityConfig.java
  src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
  src/main/java/com/kcc/pms/domain/member/mapper/MemberMapper.java
  src/main/java/com/kcc/pms/domain/member/model/vo/MemberVO.java
  src/main/java/com/kcc/pms/domain/member/service/MemberService.java
  src/main/java/com/kcc/pms/domain/member/service/MemberServiceImpl.java
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
  src/main/java/com/kcc/pms/domain/project/model/dto/ProjectManagerResponseDto.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectService.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
  src/main/java/com/kcc/pms/domain/wbs/controller/WbsController.java
  src/main/java/com/kcc/pms/init/init.java
  src/main/resources/data.sql
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/header.jsp
  src/main/webapp/WEB-INF/views/login.jsp
  src/main/webapp/WEB-INF/views/loginForm.jsp
  src/main/webapp/resources/common/css/header.css
  src/main/webapp/resources/common/images/img_login_visual.jpg
  src/main/webapp/resources/common/images/tit_login.png
  src/main/webapp/resources/member/css/login.css
  src/main/webapp/resources/member/login.css
Labels: feature

#152 [#151] 최근 프로젝트 update 구현
  src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectService.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
  src/main/resources/mapper/ProjectMapper.xml
Labels: feature

#154 [#153] 기능 목록 레이아웃 구현
  src/main/webapp/WEB-INF/views/feature/list.jsp
  src/main/webapp/resources/feature/css/featureList.css
  src/main/webapp/resources/feature/js/list.js
Labels: feature

#157 [#156] 기능페이지 전체 진척률 도넛차트, 개발자진척률, 지연목록 그리드 추가
  src/main/resources/application.yml
  src/main/webapp/WEB-INF/views/feature/list.jsp
  src/main/webapp/resources/feature/css/featureList.css
  src/main/webapp/resources/feature/js/list.js
Labels: feature

#160 [#158] 도넛프로그레스바 적용 v1
  src/main/java/com/kcc/pms/init/init.java
  src/main/webapp/WEB-INF/views/feature/list.jsp
  src/main/webapp/resources/feature/css/featureList.css
  src/main/webapp/resources/feature/js/circle-progress.min.js
  src/main/webapp/resources/feature/js/list.js
Labels: refactor

#161 [#148] 결함 관리 도메인 API 구현
  src/main/java/com/kcc/pms/domain/common/config/EnvVariableProperties.java
  src/main/java/com/kcc/pms/domain/common/mapper/CommonMapper.java
  src/main/java/com/kcc/pms/domain/common/model/dto/FileResponseDto.java
  src/main/java/com/kcc/pms/domain/common/model/vo/FileMasterNumbers.java
  src/main/java/com/kcc/pms/domain/common/service/CommonService.java
  src/main/java/com/kcc/pms/domain/common/service/CommonServiceImpl.java
  src/main/java/com/kcc/pms/domain/common/util/AwsS3Utils.java
  src/main/java/com/kcc/pms/domain/output/mapper/FileMapper.java
  src/main/java/com/kcc/pms/domain/system/controller/SystemController.java
  src/main/java/com/kcc/pms/domain/task/defect/controller/DefectController.java
  src/main/java/com/kcc/pms/domain/task/defect/domain/dto/DefectDto.java
  src/main/java/com/kcc/pms/domain/task/defect/domain/dto/DefectFileRequestDto.java
  src/main/java/com/kcc/pms/domain/task/defect/domain/dto/DefectResponseDto.java
  src/main/java/com/kcc/pms/domain/task/defect/mapper/DefectMapper.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectService.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/mapper/DefectMapper.xml
  src/main/resources/mapper/common/CommonMapper.xml
  src/main/resources/mapper/common/FileMapper.xml
  src/main/resources/mapper/member/TeamMapper.xml
  src/main/resources/mapper/task/DefectMapper.xml
  src/main/resources/mapper/task/RiskMapper.xml
  src/main/webapp/WEB-INF/views/defect/defect.jsp
  src/main/webapp/WEB-INF/views/defect/list.jsp
  src/main/webapp/resources/defect/css/defect.css
  src/main/webapp/resources/defect/css/list.css
  src/main/webapp/resources/defect/js/defect.js
  src/main/webapp/resources/defect/js/list.js
  src/main/webapp/resources/test/js/list.js
Labels: refactor, feature

#162 [#155] 로그인 시 대시 보드 연결 및 WBS 진척률과 프로젝트 진척률 연결 작업
  src/main/java/com/kcc/pms/auth/SecurityConfig.java
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
  src/main/java/com/kcc/pms/domain/project/model/dto/RecentProjectDto.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectService.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
  src/main/resources/mapper/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
  src/main/webapp/resources/project/js/list.js
  src/main/webapp/resources/wbs/css/wbsInfo.css
  src/main/webapp/resources/wbs/js/wbsInfo.js
  src/main/webapp/resources/wbs/js/wbsList.js
Labels: refactor, feature

#165 [#noissue] db 호스트명 조정
  src/main/resources/application.yml
Labels: refactor

#167 2차 배포 테스트
  src/main/resources/application.yml
Labels: refactor

#166 [#noissue] 서버 로깅 레벨 변경
  src/main/resources/application.yml
Labels: setting

#168 3차 배포 테스트
  src/main/resources/application.yml
Labels: refactor

#171 [#noissue] sql 초기화 수정
  src/main/resources/application.yml
Labels: refactor

#172 5차 배포 테스트
  src/main/resources/application.yml
Labels: refactor

#173 [#noissue] 서버 환경 분리
  src/main/resources/application.yml
Labels: refactor

#174 6차 배포 테스트
  Dockerfile
  src/main/resources/application.yml
Labels: refactor

#175 [#noissue] 배포 방식 war로 변경
  Dockerfile
  pom.xml
  src/main/java/com/kcc/pms/PmsApplication.java
  src/main/resources/application.yml
Labels: refactor, feature

#176 7차 배포 테스트
  Dockerfile
  pom.xml
  src/main/java/com/kcc/pms/PmsApplication.java
  src/main/resources/application.yml
Labels: refactor, feature

#177 Update Dockerfile
  Dockerfile
Labels: refactor

#178 [#163] WBS 인원등록 팝업 변경 권한 코드 공통 변수 생성
  src/main/java/com/kcc/pms/auth/SecurityConfig.java
  src/main/java/com/kcc/pms/domain/team/controller/TeamController.java
  src/main/java/com/kcc/pms/init/init.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/webapp/WEB-INF/views/header.jsp
  src/main/webapp/WEB-INF/views/member/list.jsp
  src/main/webapp/resources/project/js/info.js
  src/main/webapp/resources/wbs/css/wbsInfo.css
  src/main/webapp/resources/wbs/js/wbsInfo.js
Labels: refactor

#180 [#159] 기능 목록 클라이언트 및 서버 일부 구현
  src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
  src/main/java/com/kcc/pms/domain/feature/mapper/FeatureMapper.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/FeatureProgressResponseDto.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/FeatureSummaryResponseDto.java
  src/main/java/com/kcc/pms/domain/feature/service/FeatureService.java
  src/main/java/com/kcc/pms/domain/feature/service/FeatureServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/FeatureMapper.xml
  src/main/webapp/WEB-INF/views/feature/featureInfo.jsp
  src/main/webapp/WEB-INF/views/feature/list.jsp
  src/main/webapp/resources/feature/css/featureList.css
  src/main/webapp/resources/feature/js/featureInfo.js
  src/main/webapp/resources/feature/js/list.js
Labels: feature

#185 [#179] 대시보드 구현
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/java/com/kcc/pms/domain/project/mapper/ProjectMapper.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectService.java
  src/main/java/com/kcc/pms/domain/project/service/ProjectServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mapper/ProjectMapper.xml
  src/main/webapp/WEB-INF/views/project/dashboard.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
  src/main/webapp/resources/feature/css/featureList.css
  src/main/webapp/resources/project/css/dashboard.css
  src/main/webapp/resources/project/js/dashboard.js
  src/main/webapp/resources/project/js/info.js
  src/main/webapp/resources/wbs/js/wbsInfo.js
Labels: feature

#186 [#184] 팀트리 열린구조 유지
  src/main/webapp/resources/member/css/list.css
  src/main/webapp/resources/member/js/list.js
Labels: fix

#188 [#187] 기능관리 좌측패널 및 중앙패널 구현
  src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
  src/main/java/com/kcc/pms/domain/feature/mapper/FeatureMapper.java
  src/main/java/com/kcc/pms/domain/feature/service/FeatureService.java
  src/main/java/com/kcc/pms/domain/feature/service/FeatureServiceImpl.java
  src/main/java/com/kcc/pms/domain/system/controller/SystemController.java
  src/main/java/com/kcc/pms/domain/system/mapper/SystemMapper.java
  src/main/java/com/kcc/pms/domain/system/model/dto/SystemPageDto.java
  src/main/java/com/kcc/pms/domain/system/service/SystemService.java
  src/main/java/com/kcc/pms/domain/system/service/SystemServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/FeatureMapper.xml
  src/main/resources/mapper/SystemMapper.xml
  src/main/webapp/WEB-INF/views/feature/list.jsp
  src/main/webapp/resources/feature/css/featureList.css
  src/main/webapp/resources/feature/js/list.js
Labels: feature

#192 [#191] 프로젝트 PM 조회 수정 및 더미 데이터 추가
  src/main/resources/data.sql
  src/main/resources/mapper/ProjectMapper.xml
  src/main/webapp/resources/project/css/list.css
  src/main/webapp/resources/wbs/css/wbsList.css
  src/main/webapp/resources/wbs/js/wbsList.js
Labels: refactor, feature

#194 [#189] 기능 상세 조회 및 수정
  src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
  src/main/java/com/kcc/pms/domain/feature/mapper/FeatureMapper.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/FeatureCreateRequestDto.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/FeatureDetailResponseDto.java
  src/main/java/com/kcc/pms/domain/feature/service/FeatureService.java
  src/main/java/com/kcc/pms/domain/feature/service/FeatureServiceImpl.java
  src/main/resources/mapper/FeatureMapper.xml
  src/main/webapp/WEB-INF/views/feature/featureInfo.jsp
  src/main/webapp/resources/feature/js/featureInfo.js
  src/main/webapp/resources/feature/js/list.js
Labels: feature

#196 [#128] 산출물 서버 API 로직 구현
  src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
  src/main/java/com/kcc/pms/domain/common/service/CommonService.java
  src/main/java/com/kcc/pms/domain/common/service/CommonServiceImpl.java
  src/main/java/com/kcc/pms/domain/common/util/JsonParser.java
  src/main/java/com/kcc/pms/domain/output/controller/OutputController.java
  src/main/java/com/kcc/pms/domain/output/domain/dto/DeleteOutputResponseDto.java
  src/main/java/com/kcc/pms/domain/output/domain/dto/FileStructResponseDto.java
  src/main/java/com/kcc/pms/domain/output/domain/dto/OutputFile.java
  src/main/java/com/kcc/pms/domain/output/domain/dto/OutputRequestDto.java
  src/main/java/com/kcc/pms/domain/output/domain/dto/OutputResponseDto.java
  src/main/java/com/kcc/pms/domain/output/domain/dto/TaskOutput.java
  src/main/java/com/kcc/pms/domain/output/mapper/FileMapper.java
  src/main/java/com/kcc/pms/domain/output/mapper/OutputMapper.java
  src/main/java/com/kcc/pms/domain/output/service/OutputService.java
  src/main/java/com/kcc/pms/domain/output/service/OutputServiceImpl.java
  src/main/java/com/kcc/pms/domain/task/defect/controller/DefectController.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectService.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/OutputMapper.xml
  src/main/resources/mapper/common/FileMapper.xml
  src/main/webapp/WEB-INF/views/output/file/file-task.jsp
  src/main/webapp/WEB-INF/views/output/file/file.jsp
  src/main/webapp/WEB-INF/views/output/list.jsp
  src/main/webapp/WEB-INF/views/output/modal/file-insert-modal.jsp
  src/main/webapp/WEB-INF/views/output/modal/folder-modal.jsp
  src/main/webapp/WEB-INF/views/output/modal/output-file-insert.jsp
  src/main/webapp/resources/defect/js/defect.js
  src/main/webapp/resources/output/css/list.css
  src/main/webapp/resources/output/js/jstree.js
  src/main/webapp/resources/output/js/list.js
Labels: refactor, feature

#197 [#193] 프로젝트 진척률 수정 및 WBS 높이 수정
  src/main/webapp/WEB-INF/views/project/list.jsp
  src/main/webapp/resources/project/js/info.js
  src/main/webapp/resources/wbs/css/wbsList.css
  src/main/webapp/resources/wbs/js/wbsList.js
Labels: refactor

#199 [#128] wbs 작업 등록을 위한 산출물 검색 팝업 구현
  src/main/java/com/kcc/pms/domain/output/controller/OutputController.java
  src/main/webapp/WEB-INF/views/output/output-search.jsp
  src/main/webapp/resources/output/images/right.png
  src/main/webapp/resources/wbs/js/wbsInfo.js
Labels: feature

#203 [#200] 결함 로직 개선 및 파일명 UUID 미적용 개선
  src/main/java/com/kcc/pms/domain/common/service/CommonServiceImpl.java
  src/main/java/com/kcc/pms/domain/task/defect/controller/DefectController.java
  src/main/java/com/kcc/pms/domain/task/defect/domain/dto/DefectDto.java
  src/main/java/com/kcc/pms/domain/task/defect/mapper/DefectMapper.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectService.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/task/DefectMapper.xml
  src/main/webapp/WEB-INF/views/defect/defect.jsp
  src/main/webapp/WEB-INF/views/feature/featureInfo.jsp
  src/main/webapp/resources/defect/css/defect.css
  src/main/webapp/resources/defect/js/defect.js
  src/main/webapp/resources/defect/js/list.js
Labels: refactor

#204 [#200] 결함 페이징 처리 구현 & 산출물 다운로드 로직 구현
  pom.xml
  src/main/java/com/kcc/pms/domain/common/controller/CommonController.java
  src/main/java/com/kcc/pms/domain/common/service/CommonService.java
  src/main/java/com/kcc/pms/domain/common/service/CommonServiceImpl.java
  src/main/java/com/kcc/pms/domain/common/util/AwsS3Utils.java
  src/main/java/com/kcc/pms/domain/output/controller/OutputController.java
  src/main/java/com/kcc/pms/domain/output/domain/dto/DeleteOutputResponseDto.java
  src/main/java/com/kcc/pms/domain/output/domain/dto/OutputDownloadRequestDto.java
  src/main/java/com/kcc/pms/domain/output/domain/dto/OutputFile.java
  src/main/java/com/kcc/pms/domain/task/defect/controller/DefectController.java
  src/main/java/com/kcc/pms/domain/task/defect/domain/dto/DefectPageResponseDto.java
  src/main/java/com/kcc/pms/domain/task/defect/mapper/DefectMapper.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectService.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
  src/main/resources/mapper/OutputMapper.xml
  src/main/resources/mapper/task/DefectMapper.xml
  src/main/webapp/WEB-INF/views/defect/list.jsp
  src/main/webapp/WEB-INF/views/output/list.jsp
  src/main/webapp/resources/defect/js/list.js
  src/main/webapp/resources/output/js/list.js
  src/main/webapp/resources/test/js/list.js
Labels: refactor, feature

#205 [#195] 기능관리 검색 및 페이징 구현 & 기능등록 시 해당 내용으로 reload
  src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
  src/main/java/com/kcc/pms/domain/feature/mapper/FeatureMapper.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/CriteriaY.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/FeatureCreateRequestDto.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/FeatureDetailResponseDto.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/PageYDto.java
  src/main/java/com/kcc/pms/domain/feature/model/dto/PagedResponse.java
  src/main/java/com/kcc/pms/domain/feature/service/FeatureService.java
  src/main/java/com/kcc/pms/domain/feature/service/FeatureServiceImpl.java
  src/main/resources/mapper/FeatureMapper.xml
  src/main/webapp/WEB-INF/views/feature/list.jsp
  src/main/webapp/resources/feature/css/featureList.css
  src/main/webapp/resources/feature/js/featureInfo.js
  src/main/webapp/resources/feature/js/list.js
Labels: feature

#207 [#202] WBS와 산출물 연결 작업
  src/main/java/com/kcc/pms/domain/wbs/controller/WbsController.java
  src/main/java/com/kcc/pms/domain/wbs/mapper/WbsMapper.java
  src/main/java/com/kcc/pms/domain/wbs/model/dto/WbsRequestDto.java
  src/main/java/com/kcc/pms/domain/wbs/model/dto/WbsResponseDto.java
  src/main/java/com/kcc/pms/domain/wbs/service/WbsService.java
  src/main/java/com/kcc/pms/domain/wbs/service/WbsServiceImpl.java
  src/main/resources/mapper/WbsMapper.xml
  src/main/webapp/WEB-INF/views/output/output-search.jsp
  src/main/webapp/WEB-INF/views/wbs/wbsInfo.jsp
  src/main/webapp/resources/member/js/teamMemberRegister.js
  src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
  src/main/webapp/resources/wbs/css/wbsInfo.css
  src/main/webapp/resources/wbs/js/wbsInfo.js
Labels: feature

#210 [#209] 결함 공통 코드 로직 개선 & 사용자 선택 기능추가
  src/main/java/com/kcc/pms/domain/task/defect/controller/DefectController.java
  src/main/java/com/kcc/pms/domain/task/defect/domain/dto/DefectDto.java
  src/main/java/com/kcc/pms/domain/task/defect/mapper/DefectMapper.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectService.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/task/DefectMapper.xml
  src/main/webapp/WEB-INF/views/defect/defect.jsp
  src/main/webapp/WEB-INF/views/defect/list.jsp
  src/main/webapp/WEB-INF/views/test/list.jsp
  src/main/webapp/resources/defect/js/defect.js
  src/main/webapp/resources/defect/js/list.js
  src/main/webapp/resources/member/js/teamMemberRegister.js
  src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
  src/main/webapp/resources/output/js/jstree.js
  src/main/webapp/resources/output/js/list.js
  src/main/webapp/resources/test/js/list.js
Labels: refactor, feature

#211 [#208] 대시보드 수정 및 시스템 레이아웃 작업
  src/main/java/com/kcc/pms/domain/project/controller/ProjectController.java
  src/main/java/com/kcc/pms/domain/system/controller/SystemController.java
  src/main/webapp/WEB-INF/views/common.jsp
  src/main/webapp/WEB-INF/views/project/dashboard.jsp
  src/main/webapp/WEB-INF/views/system/list.jsp
  src/main/webapp/resources/project/js/dashboard.js
  src/main/webapp/resources/project/js/info.js
  src/main/webapp/resources/system/css/list.css
  src/main/webapp/resources/system/js/list.js
Labels: feature

#215 [#214] 충돌 해결
  src/main/java/com/kcc/pms/domain/feature/controller/FeatureController.java
  src/main/java/com/kcc/pms/domain/feature/mapper/FeatureMapper.java
  src/main/java/com/kcc/pms/domain/feature/service/FeatureService.java
  src/main/resources/application.yml
  src/main/resources/mapper/FeatureMapper.xml
  src/main/webapp/WEB-INF/views/feature/list.jsp
  src/main/webapp/resources/feature/css/featureList.css
  src/main/webapp/resources/feature/js/featureInfo.js
  src/main/webapp/resources/feature/js/list.js
  src/main/webapp/resources/wbs/js/wbsInfo.js
Labels: fix

#216 [#206] 위험 생성 및 수정
  src/main/java/com/kcc/pms/domain/risk/controller/RiskController.java
  src/main/java/com/kcc/pms/domain/risk/mapper/RiskMapper.java
  src/main/java/com/kcc/pms/domain/risk/model/dto/RiskDto.java
  src/main/java/com/kcc/pms/domain/risk/model/dto/RiskFileRequestDto.java
  src/main/java/com/kcc/pms/domain/risk/service/RiskService.java
  src/main/java/com/kcc/pms/domain/risk/service/RiskServiceImpl.java
  src/main/java/com/kcc/pms/domain/task/danger/controller/DangerController.java
  src/main/resources/mapper/task/RiskMapper.xml
  src/main/webapp/WEB-INF/views/danger/info.jsp
  src/main/webapp/resources/danger/js/danger.js
  src/main/webapp/resources/danger/js/info.js
  src/main/webapp/resources/issue/css/info.css
Labels: feature

#219 [#218] 코드 기본 경로 제거 및 운영환경 유연화
  src/main/java/com/kcc/pms/domain/task/defect/controller/DefectController.java
  src/main/java/com/kcc/pms/domain/task/defect/service/DefectServiceImpl.java
  src/main/java/com/kcc/pms/domain/test/controller/TestController.java
  src/main/java/com/kcc/pms/domain/test/domain/dto/TestDto.java
  src/main/java/com/kcc/pms/domain/test/domain/dto/TestPageResponseDto.java
  src/main/java/com/kcc/pms/domain/test/mapper/TestMapper.java
  src/main/java/com/kcc/pms/domain/test/service/TestService.java
  src/main/java/com/kcc/pms/domain/test/service/TestServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/mapper/TestMapper.xml
  src/main/resources/mapper/task/DefectMapper.xml
  src/main/webapp/WEB-INF/views/defect/defect.jsp
  src/main/webapp/WEB-INF/views/defect/list.jsp
  src/main/webapp/WEB-INF/views/test/list.jsp
  src/main/webapp/WEB-INF/views/test/test.jsp
  src/main/webapp/resources/defect/js/defect.js
  src/main/webapp/resources/defect/js/list.js
  src/main/webapp/resources/member/js/list.js
  src/main/webapp/resources/member/js/memberRegisterGrid.js
  src/main/webapp/resources/member/js/teamMemberRegisterGrid.js
  src/main/webapp/resources/test/css/list.css
  src/main/webapp/resources/test/css/test.css
  src/main/webapp/resources/test/js/list.js
  src/main/webapp/resources/test/js/test.js
Labels: refactor

#220 [#noissue] sql 실행문 환경 분리
  src/main/resources/application.yml
Labels: refactor

#221 현 상황 코드 운영 환경에 배포 적용
  src/main/resources/application.yml
Labels: refactor

#222 [#213] WBS 및 시스템 레이아웃 수정
  src/main/java/com/kcc/pms/auth/SecurityConfig.java
  src/main/webapp/WEB-INF/views/system/list.jsp
  src/main/webapp/resources/system/css/list.css
  src/main/webapp/resources/system/js/list.js
  src/main/webapp/resources/wbs/css/wbsList.css
  src/main/webapp/resources/wbs/js/wbsList.js
Labels: refactor

#224 feat: 위험 목록 검색 및 필터링 조회 + 그리드 크기 축소 (#217)
  src/main/java/com/kcc/pms/domain/risk/controller/RiskController.java
  src/main/java/com/kcc/pms/domain/risk/mapper/RiskMapper.java
  src/main/java/com/kcc/pms/domain/risk/model/dto/CriteriaRisk.java
  src/main/java/com/kcc/pms/domain/risk/model/dto/PageRiskDto.java
  src/main/java/com/kcc/pms/domain/risk/model/dto/PagedRiskResponse.java
  src/main/java/com/kcc/pms/domain/risk/model/dto/RiskSummaryResponseDto.java
  src/main/java/com/kcc/pms/domain/risk/service/RiskService.java
  src/main/java/com/kcc/pms/domain/risk/service/RiskServiceImpl.java
  src/main/resources/mapper/FeatureMapper.xml
  src/main/resources/mapper/task/RiskMapper.xml
  src/main/webapp/WEB-INF/views/danger/danger_list.jsp
  src/main/webapp/resources/danger/css/danger.css
  src/main/webapp/resources/danger/js/danger.js
Labels: feature

#226 [#225] 위험 더미데이터 추가
  src/main/resources/data.sql
Labels: refactor

#228 [#223] 이슈 / 위험 레이아웃 수정
  src/main/webapp/WEB-INF/views/danger/danger_list.jsp
  src/main/webapp/WEB-INF/views/danger/info.jsp
  src/main/webapp/WEB-INF/views/issue/info.jsp
  src/main/webapp/WEB-INF/views/issue/list.jsp
  src/main/webapp/resources/danger/css/danger.css
  src/main/webapp/resources/issue/css/info.css
  src/main/webapp/resources/issue/js/info.js
Labels: refactor
